# Generated by Django 4.2.11 on 2024-04-23 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_group', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='user_relations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_1', models.IntegerField()),
                ('id_2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='messengers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.group')),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.group')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.users')),
            ],
        ),
    ]
