# Generated by Django 4.2.11 on 2024-04-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengers',
            name='sender_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
