# Generated by Django 4.2.11 on 2024-04-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messengers_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='updated',
            field=models.DateTimeField(default='2024-04-23 11:18:35'),
            preserve_default=False,
        ),
    ]
