# Generated by Django 4.2.11 on 2024-05-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_group_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengers',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.members'),
        ),
    ]
