# Generated by Django 4.2.11 on 2024-04-10 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_color_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='manufacturer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer'),
            preserve_default=False,
        ),
    ]
